# Generated by Django 4.0.4 on 2023-08-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVideos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitles',
            name='Subtitles',
            field=models.FileField(upload_to='Subtitles'),
        ),
        migrations.AlterField(
            model_name='video',
            name='Video',
            field=models.FileField(upload_to='Video'),
        ),
    ]
