# Generated by Django 4.0.4 on 2023-08-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVideos', '0003_remove_video_slug_video_custom_subtitles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='Custom_Subtitles',
        ),
        migrations.AddField(
            model_name='video',
            name='hey',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
