# Generated by Django 4.0.4 on 2023-08-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVideos', '0004_remove_video_custom_subtitles_video_hey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hey',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
