# Generated by Django 4.0.4 on 2023-08-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVideos', '0005_alter_video_hey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='hey',
        ),
    ]
