# Generated by Django 4.0.4 on 2023-08-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVideos', '0008_subtitles_delete_videodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='subtitles',
            field=models.FileField(blank=True, null=True, upload_to='Subtitles'),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Subtitles',
        ),
    ]
