# Generated by Django 4.0.4 on 2023-08-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVideos', '0009_video_slug_video_subtitles_video_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='custom_subtitles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
