# Generated by Django 4.0.4 on 2023-08-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVideos', '0010_video_custom_subtitles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='subtitles',
            new_name='subtitles_text',
        ),
        migrations.AddField(
            model_name='video',
            name='timestamp_end',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='timestamp_start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
