# Generated by Django 4.0.4 on 2023-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVideos', '0011_rename_subtitles_video_subtitles_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitles_file',
            field=models.FileField(blank=True, null=True, upload_to='Subtitles'),
        ),
    ]
