# Generated by Django 4.0.4 on 2023-08-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVideos', '0012_video_subtitles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subtitles_text',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
