# Generated by Django 4.0.4 on 2023-08-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVideos', '0013_alter_video_subtitles_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='custom_subtitles',
        ),
    ]
