# Generated by Django 4.0.4 on 2023-08-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVideos', '0014_remove_video_custom_subtitles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subtitles_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
